.TH "iscsi-iname" "8" "July 2006" "open-iscsi" "Debian Distribution" 
.PP 
.SH "NAME" 
iscsi-iname \- iSCSI node name generation utility
.PP 
.SH "SYNOPSIS" 
.PP 
iscsi-iname
.PP 
.SH "DESCRIPTION"
.PP
iscsi-iname generates a unique iSCSI node name on every invocation
.PP
.SH "BUGS" 
Contact Philipp Hug <debian@hug.cx>, for any bugs with this program
.PP 
.SH "AUTHOR" 
This manpage was written by Philipp Hug <debian@hug.cx>, 2006
.PP 
